In [335]:
import data
X_train, y_train, X_test, y_test = data.load_decision_tree_data()
print(X_train)
labels_count = np.bincount(y_train)
labels_count
print( np.unique(y_test))

[[0 0 2 2 0 0]
 [0 0 2 2 0 1]
 [0 0 2 2 0 2]
 ...
 [1 1 2 5 2 0]
 [1 1 2 5 2 1]
 [1 1 2 5 2 2]]
[0 1 2 3]


In [344]:
result = []
for i in range(len(X_train[0])):
    result1 = []
    for j in np.unique(np.transpose(X_train)[i]):
        labels = []
        for ind,k in enumerate(np.transpose(X_train)[i]):
            if(j == k):
                labels.append(y_train[ind])
        result1.append(np.bincount(labels).tolist())
    result.append(result1)
result

[[[360, 72], [161, 80, 0, 2], [324, 108]],
 [[432, 108], [161, 80, 0, 2], [252, 72]],
 [[238, 57, 0, 2], [207, 63], [200, 70], [200, 70]],
 [[369], [237, 131, 0, 1], [239, 129, 0, 1]],
 [[318, 51], [274, 95], [253, 114, 0, 2]],
 [[369], [273, 96], [203, 164, 0, 2]]]

In [345]:
result = []
for i in range(len(X_train[0])):
    result1 = []
    for j in np.unique(np.transpose(X_train)[i]):
        print(j)
    print('\n')

0
1
2


0
1
2


2
3
4
5


2
4
5


0
1
2


0
1
2




In [362]:
np.argmax([2,3,4,5])

3

In [365]:
labels_count = np.bincount(y_train)
h = 0.0
esum = np.sum(labels_count)
if esum == 0:
    h = 0.0
else:
    for k in labels_count:
        if k == 0:
            h1 = 0
        else:
            h1 = -k/esum*np.log2(k/esum)
        h += h1
h

0.8047719410853778

In [386]:
a = np.array([[1], [1,1], [0, 1]])
total_sum = np.sum(np.array([np.sum(i) for i in a]))
print(total_sum)

4


In [388]:
for index ,j in enumerate([1,2,3,4,5]):
    print(index, j)
    

0 1
1 2
2 3
3 4
4 5


In [402]:
import utils as Util
h = 1
i = [1]
Util.Information_Gain(h,i)

TypeError: 'int' object is not iterable

In [403]:
np.argmax([1,2,[]])

ValueError: setting an array element with a sequence.

In [416]:
list([1,2,3,4])

[1, 2, 3, 4]

In [420]:
import copy
class a():
    def __init__(self):
        self.x = 1
x = a()
y = copy.deepcopy(x)

In [424]:
np.bincount([])

array([], dtype=int64)