In [144]:
import numpy as np
np.matmul([1,2,3],np.array([[2,3,4,4],[1,2,1,2],[2,3,1,1]]))

array([10, 16,  9, 11])

In [30]:
np.multiply([2,3],[4,5])

array([ 8, 15])

In [51]:
1*np.ones(10)


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [136]:
a = np.mat([1,2,3])
b = np.ones(2)
np.matmul(a.T,np.mat(b))

matrix([[1., 1.],
        [2., 2.],
        [3., 3.]])

In [138]:
X = np.array([0,1,3,-2,5,-7])
np.where(X <= 0,X-X+1,X-X)

array([1, 0, 0, 1, 0, 1])

In [142]:
np.dot([1,3,1],[1,0,2])

3

In [147]:
a = np.array([[1,2,3],[1,2,3],[1,2,3]])
b = np.array([[1,2,2],[1,2,2],[1,2,2]])
b/a

array([[1.        , 1.        , 0.66666667],
       [1.        , 1.        , 0.66666667],
       [1.        , 1.        , 0.66666667]])

In [150]:
np.max(np.array([[1,1,1,1],[2,10,2,2],[3,3,3,4]]),axis = 0)

array([ 3, 10,  3,  4])

In [151]:
np.sum(np.array([[1,1,1,1],[2,10,2,2],[3,3,3,4]]),axis = 0)

array([ 6, 14,  6,  7])

In [162]:
c = 3
e_x = np.array([[1,3,3,4],[2,2,3,4],[3,2,3,4]])
e_x / np.matmul(np.mat(np.ones(c)).T,np.mat(np.sum(e_x,axis = 0)))

matrix([[1., 1., 1., 1.]])

In [190]:
b = np.zeros(3)
n = 6

b -= 0.5*np.matmul(np.array([[1,2,1,1,2],[1,2,1,2,1],[2,3,2,1,3]]),np.ones(5))/n
(0.5*np.matmul(np.asarray(np.mat([[1,2,1,1,2],[1,2,1,2,1],[2,3,2,1,3]])),np.ones(5))/n).shape


(3,)

In [198]:
np.argmax(np.mat([[3,10,3,4],[2,3,4,5],[3,3,5,6]]),axis = 0)*1.0

matrix([[0., 0., 2., 2.]])